jasypt:
  encryptor:
    password: ${jasyptpwd:secretkey}
    algorithm: PBEWithMD5AndDES

server:
  port: 8083
  servlet:
    context-path: /city_parking
    session:
      timeout: 21600s

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:postgresql://localhost:5432/cityparking
    username: postgres
    password: postgres
    hikari:
      poolName: pool
